/*
 * File:        QrVerificationEngineTest.kt
 * Project:     Smart Solar Microgrid Trading System (SE4040)
 * Layer:       Tests
 * Author:      H. Bhathiya (IT22189530)
 * Created:     2026-09-30
 * Description: Unit tests verifying that the QR verification engine correctly extracts
 *              and normalizes reservation reference keys across all supported QR formats.
 */

package com.example.mobileapp.operator

import org.junit.Assert.assertEquals
import org.junit.Test
import java.nio.charset.StandardCharsets
import java.util.Base64

class QrVerificationEngineTest {

    @Test
    fun extractReference_handlesProsumerAppSsmFormat() {
        // App format generated by Reservation.kt: "SSM-RSV|RSV-1001|sampleToken123"
        val raw = "SSM-RSV|RSV-1001|sampleToken123"
        assertEquals("RSV-1001", QrVerificationEngine.extractReference(raw))
    }

    @Test
    fun extractReference_handlesBase64PayloadFromBackend() {
        // Backend format: base64 of "RES-20260922-A101|200012345678|NODE-COLOMBO-01"
        val payload = "RES-20260922-A101|200012345678|NODE-COLOMBO-01"
        val base64 = Base64.getEncoder().encodeToString(payload.toByteArray(StandardCharsets.UTF_8))

        assertEquals("RES-20260922-A101", QrVerificationEngine.extractReference(base64))
    }

    @Test
    fun extractReference_handlesPipeSeparatedRawString() {
        val raw = "RES-20260922-B202|199856789012|NODE-KANDY-02|2026-10-04T14:00:00Z|40.00"
        assertEquals("RES-20260922-B202", QrVerificationEngine.extractReference(raw))
    }

    @Test
    fun extractReference_handlesDirectReservationNumber() {
        val raw = "RES-20260922-C303"
        assertEquals("RES-20260922-C303", QrVerificationEngine.extractReference(raw))
    }

    @Test
    fun extractReference_handlesMongoObjectId() {
        val raw = "66f7f0a8b9a1c2d3e4f5a6b7"
        assertEquals("66f7f0a8b9a1c2d3e4f5a6b7", QrVerificationEngine.extractReference(raw))
    }
}
