/*
 * File:        Reservation.cs
 * Project:     Smart Solar Microgrid Trading System (SE4040)
 * Layer:       Models
 * Author:      H. Bhathiya (IT22189530)
 * Created:     2026-09-22
 * Description: Document stored in the "reservations" MongoDB collection.
 *              Represents a power trading reservation created by or on behalf
 *              of a solar prosumer for energy drop-off or charging at a
 *              specific microgrid node and time slot.
 */

using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SmartSolar.Api.Models;

public static class ReservationStatus
{
    public const string Pending = "Pending";
    public const string Approved = "Approved";
    public const string Completed = "Completed";
    public const string Cancelled = "Cancelled";
}

public static class ReservationType
{
    public const string DropOff = "DropOff";
    public const string Charging = "Charging";
}

public class Reservation
{
    // MongoDB document id, generated by the database
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string? Id { get; set; }

    // Human-friendly reference number, e.g. "RES-20260922-8F2A"
    [BsonElement("reservationNumber")]
    public string ReservationNumber { get; set; } = string.Empty;

    // National Identity Card of the prosumer (primary key in prosumer profile)
    [BsonElement("prosumerNic")]
    public string ProsumerNic { get; set; } = string.Empty;

    // Name of the prosumer for display and reporting
    [BsonElement("prosumerName")]
    public string ProsumerName { get; set; } = string.Empty;

    // Identifier of the microgrid hub / solar station
    [BsonElement("nodeId")]
    public string NodeId { get; set; } = string.Empty;

    // Name or location label of the microgrid node
    [BsonElement("nodeName")]
    public string NodeName { get; set; } = string.Empty;

    // Start time of the reserved energy slot in UTC
    [BsonElement("slotStartTime")]
    public DateTime SlotStartTime { get; set; }

    // End time of the reserved energy slot in UTC
    [BsonElement("slotEndTime")]
    public DateTime SlotEndTime { get; set; }

    // Energy quantity reserved in kilowatt-hours (kW/h)
    [BsonElement("energyAmountKWh")]
    public double EnergyAmountKWh { get; set; }

    // Type of trading: "DropOff" (selling power) or "Charging" (buying power)
    [BsonElement("reservationType")]
    public string ReservationType { get; set; } = Models.ReservationType.DropOff;

    // Lifecycle state: Pending, Approved, Completed, Cancelled
    [BsonElement("status")]
    public string Status { get; set; } = ReservationStatus.Pending;

    // Secure token or QR code dispatch payload verified by grid operator on site
    [BsonElement("transactionQrCode")]
    public string TransactionQrCode { get; set; } = string.Empty;

    // Reason provided if the reservation was cancelled
    [BsonElement("cancellationReason")]
    [BsonIgnoreIfNull]
    public string? CancellationReason { get; set; }

    // Timestamp when cancellation occurred in UTC
    [BsonElement("cancelledAt")]
    [BsonIgnoreIfNull]
    public DateTime? CancelledAt { get; set; }

    // Optional operational notes or instructions
    [BsonElement("notes")]
    [BsonIgnoreIfNull]
    public string? Notes { get; set; }

    // Audit fields stored in UTC
    [BsonElement("createdAt")]
    public DateTime CreatedAt { get; set; }

    [BsonElement("updatedAt")]
    public DateTime UpdatedAt { get; set; }

    // Account or actor who placed the booking (e.g. Backoffice / Grid Operator username or NIC)
    [BsonElement("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;
}
