/*
 * File:        WebUser.cs
 * Project:     Smart Solar Microgrid Trading System (SE4040)
 * Layer:       Models
 * Author:      N. Jayasinghe (IT2XXXXXXX)
 * Created:     2026-09-20
 * Description: Document stored in the "webUsers" MongoDB collection. Represents
 *              a web application user, who is either a Backoffice officer or a
 *              Grid Operator. Prosumers are stored separately and are not
 *              represented by this class.
 */

using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SmartSolar.Api.Models;

public class WebUser
{
    // MongoDB document id, generated by the database and exposed as a string
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string? Id { get; set; }

    // Display name shown in the user list and in the navigation bar
    [BsonElement("fullName")]
    public string FullName { get; set; } = string.Empty;

    // Login name; always stored lowercase and protected by a unique index
    [BsonElement("email")]
    public string Email { get; set; } = string.Empty;

    // Short account name, stored lowercase and unique across all web users
    [BsonElement("username")]
    public string Username { get; set; } = string.Empty;

    // National Identity Card number, unique across all web users
    [BsonElement("nic")]
    public string Nic { get; set; } = string.Empty;

    // Contact telephone number
    [BsonElement("phone")]
    public string Phone { get; set; } = string.Empty;

    // Date of birth, stored in UTC. Nullable so that user documents created
    // before this field existed still load correctly.
    [BsonElement("dateOfBirth")]
    [BsonIgnoreIfNull]
    public DateTime? DateOfBirth { get; set; }

    // BCrypt hash of the password; never returned to any client
    [BsonElement("passwordHash")]
    public string PasswordHash { get; set; } = string.Empty;

    // Either "Backoffice" or "GridOperator" (see UserRoles)
    [BsonElement("role")]
    public string Role { get; set; } = string.Empty;

    // Deactivated users stay in the database but are refused at login
    [BsonElement("isActive")]
    public bool IsActive { get; set; } = true;

    // Audit fields, all stored in UTC so they are not affected by the server time zone
    [BsonElement("createdAt")]
    public DateTime CreatedAt { get; set; }

    [BsonElement("updatedAt")]
    public DateTime UpdatedAt { get; set; }

    // Id of the Backoffice user who created this record, or "system" for the seeded admin
    [BsonElement("createdBy")]
    public string CreatedBy { get; set; } = string.Empty;
}
